apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: techshop
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: techshop
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_PASSWORD: dGVjaHNob3BfcGFzc3dvcmQ=
