apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: techshop
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: techshop
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
