apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: techshop
  labels:
    app.kubernetes.io/name: message-queue
    app.kubernetes.io/part-of: techshop
    app.kubernetes.io/component: message-queue
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
